name: nowlive
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 6.0.0+2

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.10.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  chewie:
    path: packages/chewie/
  vimeo_video_player:
    path: packages/vimeo/

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  google_fonts: ^4.0.0
  buttons_tabbar: ^1.3.7
  # Players
  youtube_player_iframe: ^4.0.4
  video_player: ^2.7.0
  video_player_web_hls: ^1.0.0+3
  subtitle_wrapper_package: ^2.1.1
  # Players
  # Payment Gateways
  razorpay_web: ^1.3.5
  paytm_allinonesdk: ^1.2.1
  flutter_stripe: ^10.1.1
  flutter_dotenv: ^5.1.0
  http_auth: ^1.0.2
  flutter_paypal: ^0.2.0
  flutterwave_standard: ^1.0.4
  uuid: ^4.0.0
  # payu_checkoutpro_flutter: ^1.0.4
  pay_with_paystack: ^1.0.6
  # Payment Gateways
  # Firebase - OneSignal
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  google_sign_in: ^6.1.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_auth_platform_interface: ^7.1.8
  onesignal_flutter: ^5.0.0
  firebase_messaging: ^14.6.7
  google_mobile_ads: ^4.0.0
  # Firebase - OneSignal
  intl_phone_field: ^3.2.0
  http: ^0.13.6
  pinput: ^4.0.0
  intl: ^0.18.1
  flutter_locales: ^3.0.1
  image_picker: ^1.0.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.1.0
  percent_indicator: ^4.2.3
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  progress_dialog_null_safe: ^2.0.0
  expandable_text: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  expandable: ^5.0.1
  flutter_inappwebview: ^5.7.2+3
  flutter_html: ^3.0.0-alpha.3
  url_launcher: ^6.1.11
  bottom_navy_bar: ^6.0.0
  shimmer: ^3.0.0
  shimmer_animation: ^2.1.0+1
  speech_to_text: ^6.1.1
  avatar_glow: ^3.0.1
  flutter_share: ^2.0.0
  path_provider: ^2.0.15
  path: ^1.8.2
  html: ^0.15.4
  social_share: ^2.3.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  scrollable_positioned_list: ^0.3.8
  pull_to_refresh: ^2.0.0
  permission_handler: ^11.3.1
  responsive_framework: ^1.0.0
  dropdown_button2: ^2.0.0
  universal_html: ^2.0.9
  js: ^0.6.5
  responsive_grid_list: ^1.3.2
  flutter_cors: ^1.4.0
  device_info_plus: ^8.1.0
  flutter_downloader: ^1.10.2
  random_string: ^2.3.1
  flutter_secure_storage: ^8.0.0
  scrollview_observer: ^1.14.0
  flutter_pagewise: ^2.0.4
  connectivity_plus: ^6.0.1
  marquee: ^2.2.3
  numeral: ^3.0.0
  gradient_borders: ^1.0.0
  screen_protector: ^1.2.0
  g_recaptcha_v3: ^0.0.5

dependency_overrides:
  webview_flutter_wkwebview: '3.5.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Ngreen.png"  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/locales/en.json
    - assets/locales/af.json
    - assets/locales/ar.json
    - assets/locales/de.json
    - assets/locales/es.json
    - assets/locales/fr.json
    - assets/locales/gu.json
    - assets/locales/hi.json
    - assets/locales/id.json
    - assets/locales/nl.json
    - assets/locales/pt.json
    - assets/locales/sq.json
    - assets/locales/tr.json
    - assets/locales/vi.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
